Repository michaelrsweet/pappl, pull requests merged in 2024-01, with the labels that each got.

#318 configure.ac: Fix --enable-libpam option
  configure
  configure.ac
Labels: bug, priority-low

#320 device-network.c: Fix crash in `pappl_dnssd_list()` with Avahi
  pappl/device-network.c
Labels: bug, priority-medium

#319 device-network.c: Fix crash in `pappl_dnssd_list()` with Avahi
  pappl/device-network.c
Labels: bug, priority-medium

#326 Typo fixes (v1.4.x branch)
  SECURITY.md
  doc/pappl-body.md
  doc/pappl.html
  man/pappl-printer.3
  man/pappl-system.3
  pappl/Makefile
  pappl/client-auth.c
  pappl/client-ipp.c
  pappl/client.c
  pappl/device-network.c
  pappl/dnssd.c
  pappl/job-ipp.c
  pappl/loc.c
  pappl/log.c
  pappl/lookup.c
  pappl/mainloop-subcommands.c
  pappl/mainloop-support.c
  pappl/printer-webif.c
  pappl/printer.c
  pappl/subscription-private.h
  pappl/subscription.c
  pappl/system-accessors.c
  pappl/system-loadsave.c
  pappl/system-webif.c
Labels: documentation

#325 Typo fixes (master branch)
  SECURITY.md
  doc/pappl-body.md
  doc/pappl.html
  man/pappl-printer.3
  man/pappl-system.3
  pappl/Makefile
  pappl/client-auth.c
  pappl/client-ipp.c
  pappl/client.c
  pappl/job-ipp.c
  pappl/job-private.h
  pappl/job-process.c
  pappl/loc.c
  pappl/log.c
  pappl/lookup.c
  pappl/mainloop-subcommands.c
  pappl/mainloop-support.c
  pappl/printer-support.c
  pappl/printer-webif.c
  pappl/printer.c
  pappl/subscription-private.h
  pappl/subscription.c
  pappl/system-accessors.c
  pappl/system-loadsave.c
  pappl/system-webif.c
Labels: documentation
